//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteImaging.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ImageOutput")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
            set {
                this["OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BigPic")]
        public string BigImageDirectoryName {
            get {
                return ((string)(this["BigImageDirectoryName"]));
            }
            set {
                this["BigImageDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Icon")]
        public string IconDirectoryName {
            get {
                return ((string)(this["IconDirectoryName"]));
            }
            set {
                this["IconDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video")]
        public string VideoDirectoryName {
            get {
                return ((string)(this["VideoDirectoryName"]));
            }
            set {
                this["VideoDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\UploadPool")]
        public string ImageUploadPool {
            get {
                return ((string)(this["ImageUploadPool"]));
            }
            set {
                this["ImageUploadPool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ColumnNumber {
            get {
                return ((int)(this["ColumnNumber"]));
            }
            set {
                this["ColumnNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CamConfig.xml")]
        public string CamConfigFile {
            get {
                return ((string)(this["CamConfigFile"]));
            }
            set {
                this["CamConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int LengthOfImageGroup {
            get {
                return ((int)(this["LengthOfImageGroup"]));
            }
            set {
                this["LengthOfImageGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string IconLeftExtRatio {
            get {
                return ((string)(this["IconLeftExtRatio"]));
            }
            set {
                this["IconLeftExtRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string IconRightExtRatio {
            get {
                return ((string)(this["IconRightExtRatio"]));
            }
            set {
                this["IconRightExtRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string IconTopExtRatio {
            get {
                return ((string)(this["IconTopExtRatio"]));
            }
            set {
                this["IconTopExtRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string IconBottomExtRatio {
            get {
                return ((string)(this["IconBottomExtRatio"]));
            }
            set {
                this["IconBottomExtRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string MinFaceWidth {
            get {
                return ((string)(this["MinFaceWidth"]));
            }
            set {
                this["MinFaceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public string DownSampling {
            get {
                return ((string)(this["DownSampling"]));
            }
            set {
                this["DownSampling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SrchRegionLeft {
            get {
                return ((string)(this["SrchRegionLeft"]));
            }
            set {
                this["SrchRegionLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SrchRegionTop {
            get {
                return ((string)(this["SrchRegionTop"]));
            }
            set {
                this["SrchRegionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public string SrchRegionWidth {
            get {
                return ((string)(this["SrchRegionWidth"]));
            }
            set {
                this["SrchRegionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\VideoDownLoadTool\\HDCDownloader.exe")]
        public string VideoDnTool {
            get {
                return ((string)(this["VideoDnTool"]));
            }
            set {
                this["VideoDnTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public string SrchRegionHeight {
            get {
                return ((string)(this["SrchRegionHeight"]));
            }
            set {
                this["SrchRegionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EnvMode {
            get {
                return ((int)(this["EnvMode"]));
            }
            set {
                this["EnvMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string FPs {
            get {
                return ((string)(this["FPs"]));
            }
            set {
                this["FPs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawMotionRect {
            get {
                return ((bool)(this["DrawMotionRect"]));
            }
            set {
                this["DrawMotionRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DetectMotion {
            get {
                return ((bool)(this["DetectMotion"]));
            }
            set {
                this["DetectMotion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool removeDuplicatedFace {
            get {
                return ((bool)(this["removeDuplicatedFace"]));
            }
            set {
                this["removeDuplicatedFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxDupFaces {
            get {
                return ((int)(this["MaxDupFaces"]));
            }
            set {
                this["MaxDupFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastSelCamID {
            get {
                return ((int)(this["LastSelCamID"]));
            }
            set {
                this["LastSelCamID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrightMode {
            get {
                return ((int)(this["BrightMode"]));
            }
            set {
                this["BrightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string ComName {
            get {
                return ((string)(this["ComName"]));
            }
            set {
                this["ComName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.6")]
        public string CurIp {
            get {
                return ((string)(this["CurIp"]));
            }
            set {
                this["CurIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Thresholding {
            get {
                return ((int)(this["Thresholding"]));
            }
            set {
                this["Thresholding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ImageArr {
            get {
                return ((int)(this["ImageArr"]));
            }
            set {
                this["ImageArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600 110 700 1200  ")]
        public string Point {
            get {
                return ((string)(this["Point"]));
            }
            set {
                this["Point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string MaxFaceWidth {
            get {
                return ((string)(this["MaxFaceWidth"]));
            }
            set {
                this["MaxFaceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2false")]
        public string SaveDay {
            get {
                return ((string)(this["SaveDay"]));
            }
            set {
                this["SaveDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Temp {
            get {
                return ((string)(this["Temp"]));
            }
            set {
                this["Temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WarnPicSavePath {
            get {
                return ((string)(this["WarnPicSavePath"]));
            }
            set {
                this["WarnPicSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WarnInfoHandleMode {
            get {
                return ((int)(this["WarnInfoHandleMode"]));
            }
            set {
                this["WarnInfoHandleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImpPersonConfigure.xml")]
        public string ImpPersonConfigure {
            get {
                return ((string)(this["ImpPersonConfigure"]));
            }
            set {
                this["ImpPersonConfigure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\faceRecognition\\selectedFace\\")]
        public string ImpSelectPersonPath {
            get {
                return ((string)(this["ImpSelectPersonPath"]));
            }
            set {
                this["ImpSelectPersonPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FaceStoregePath {
            get {
                return ((string)(this["FaceStoregePath"]));
            }
            set {
                this["FaceStoregePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5,0.58|0.58,0.68|0.68,1")]
        public string SimilarityLevel {
            get {
                return ((string)(this["SimilarityLevel"]));
            }
            set {
                this["SimilarityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string ReservedDiskSpaceMB {
            get {
                return ((string)(this["ReservedDiskSpaceMB"]));
            }
            set {
                this["ReservedDiskSpaceMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\faceRecognition\\faceSample\\")]
        public string FaceSampleLib {
            get {
                return ((string)(this["FaceSampleLib"]));
            }
            set {
                this["FaceSampleLib"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecheckFace {
            get {
                return ((bool)(this["RecheckFace"]));
            }
            set {
                this["RecheckFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFaceRecognizeButton {
            get {
                return ((bool)(this["ShowFaceRecognizeButton"]));
            }
            set {
                this["ShowFaceRecognizeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeepMotionLessVideo {
            get {
                return ((bool)(this["KeepMotionLessVideo"]));
            }
            set {
                this["KeepMotionLessVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int FreeDiskspaceCheckIntervalMs {
            get {
                return ((int)(this["FreeDiskspaceCheckIntervalMs"]));
            }
            set {
                this["FreeDiskspaceCheckIntervalMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MaxFrameQueueLength {
            get {
                return ((int)(this["MaxFrameQueueLength"]));
            }
            set {
                this["MaxFrameQueueLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string HostId {
            get {
                return ((string)(this["HostId"]));
            }
            set {
                this["HostId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未命名监控点")]
        public string HostName {
            get {
                return ((string)(this["HostName"]));
            }
            set {
                this["HostName"] = value;
            }
        }
    }
}
